language: java
jobs:
  include:
    - stage: Run tests
      script : mvn test
    - stage: Deploy staging
      deploy:
        provider: heroku
        api_key: ad6c220d-e6e2-442a-bec1-2243f1e6fefc
        app: demo-ci-gina
    - stage: Ping Staging
      script: 'curl https://demo-ci-gina.herokuapp.com/v1/prueba'
    - stage: Deploy production
      deploy:
        provider: heroku
        api_key: ad6c220d-e6e2-442a-bec1-2243f1e6fefc
        app: demo-ci-gina-production
    - stage: Ping production
      script: 'curl https://demo-ci-gina-production.herokuapp.com/v1/prueba'
before_install:
  - chmod +x mvnw